# Generated by Django 4.2.4 on 2023-09-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionToQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koefficient_calculator.profession')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koefficient_calculator.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionToExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koefficient_calculator.experience')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koefficient_calculator.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Koefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=255)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koefficient_calculator.experience')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koefficient_calculator.profession')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koefficient_calculator.qualification')),
            ],
        ),
    ]
