# Generated by Django 4.2.4 on 2023-09-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koefficient_calculator', '0001_initial'),
        ('employees', '0002_remove_employee_experience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Teacher',
        ),
    ]
