# Generated by Django 4.2.4 on 2023-09-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koefficient_calculator', '0001_initial'),
        ('employees', '0003_rename_employee_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='koefficient_calculator.profession'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='koefficient_calculator.qualification'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_experience_years',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
