# Generated by Django 4.2.4 on 2023-10-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_teacher_profession_teacher_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_experience_years',
        ),
    ]
