# Generated by Django 4.2.4 on 2023-10-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_teacher_birth_date_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='koefficient',
        ),
    ]
