# Generated by Django 4.2.4 on 2023-10-23 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_teacher_koefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
