# Generated by Django 4.2.4 on 2023-10-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_teacher_date_created_teacher_date_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name']},
        ),
    ]
