# Generated by Django 4.2.4 on 2023-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burelis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burelis',
            name='valandu_skaicius',
            field=models.IntegerField(max_length=255),
        ),
    ]
