# Generated by Django 4.2.4 on 2023-11-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_teacher_options'),
        ('burelis', '0002_alter_burelis_valandu_skaicius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burelis',
            name='mokytojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.teacher'),
        ),
        migrations.AlterField(
            model_name='burelis',
            name='valandu_skaicius',
            field=models.IntegerField(),
        ),
    ]
