# Generated by Django 4.2.4 on 2023-09-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('contactless_percent_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_contact_hours', models.IntegerField(null=True)),
                ('contactless_hours', models.IntegerField(null=True)),
                ('total_hours', models.IntegerField(null=True)),
                ('etato_dalis', models.FloatField(null=True)),
                ('contactless_hour_percent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactless_percent_calculator.contactlesshourpercent')),
            ],
        ),
        migrations.CreateModel(
            name='ContactClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.CharField(choices=[('1-4', 'Kontaktinės 1-4 kl.'), ('5-8', 'Kontaktinės 5-8 kl.')], max_length=100)),
                ('student_count', models.CharField(choices=[('12-20', '12-20 mokinių klasėje'), ('21', '21 ir daugiau mokinių klasėje')], max_length=100)),
                ('classes_count', models.IntegerField()),
                ('wrokload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workload_calculator.workload')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityToWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('workload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workload_calculator.workload')),
            ],
        ),
    ]
