# Generated by Django 4.2.4 on 2023-10-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_calculator', '0003_rename_class_grade_contactclasses_grade_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactclasses',
            name='wrokload',
        ),
        migrations.AddField(
            model_name='contactclasses',
            name='workload',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workload_calculator.workload'),
        ),
    ]
