# Generated by Django 4.2.4 on 2023-10-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_calculator', '0004_remove_contactclasses_wrokload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytoworkload',
            name='activity',
        ),
    ]
