# Generated by Django 4.2.4 on 2023-09-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactlessHourPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_subject', models.CharField(choices=[('Pradinis ugdymas', 'Pradinis ugdymas'), ('Pagrindinis ir vidurinis ugdymas', 'Pagrindinis ir vidurinis ugdymas'), ('Dorinis ugdymas', 'Dorinis ugdymas'), ('Lietuvių kalba, gimtoji kalba', 'Lietuvių kalba, gimtoji kalba'), ('Užsienio kalba', 'Užsienio kalba'), ('Matematika', 'Matematika'), ('Informacinės technologijos', 'Informacinės technologijos'), ('Gamtamokslinis ugdymas', 'Gamtamokslinis ugdymas'), ('Socialinis ugdymas', 'Socialinis ugdymas'), ('Menai, technologijos, kūno kultūra...', 'Menai, technologijos, kūno kultūra...'), ('Neformalusis švietimas', 'Neformalusis švietimas')], max_length=255)),
                ('work_experience_period', models.CharField(choices=[('iki 2 metų', 'iki 2 metų'), ('daugiau nei 2 metai', 'daugiau nei 2 metai')], max_length=255)),
                ('student_count', models.CharField(choices=[('ne daugiau kaip 11', 'ne daugiau kaip 11'), ('12-20', '12-20'), ('21 ir daugiau', '21 ir daugiau')], max_length=255)),
                ('percent', models.FloatField()),
            ],
        ),
    ]
