# Generated by Django 4.2.4 on 2023-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactless_percent_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlesshourpercent',
            name='teaching_subject',
            field=models.CharField(choices=[('Pradinis ugdymas', 'Pradinis ugdymas'), ('Dorinis ugdymas', 'Dorinis ugdymas'), ('Lietuvių kalba, gimtoji kalba', 'Lietuvių kalba, gimtoji kalba'), ('Užsienio kalba', 'Užsienio kalba'), ('Matematika', 'Matematika'), ('Informacinės technologijos', 'Informacinės technologijos'), ('Gamtamokslinis ugdymas', 'Gamtamokslinis ugdymas'), ('Socialinis ugdymas', 'Socialinis ugdymas'), ('Menai, technologijos, kūno kultūra...', 'Menai, technologijos, kūno kultūra...'), ('Neformalusis švietimas', 'Neformalusis švietimas')], max_length=255),
        ),
    ]
