# Generated by Django 4.2.4 on 2023-10-23 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactless_percent_calculator', '0002_alter_contactlesshourpercent_teaching_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlesshourpercent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactlesshourpercent',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
