# Generated by Django 4.2.4 on 2023-10-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclasstoteacher',
            name='student',
        ),
        migrations.AddField(
            model_name='studentclasstoteacher',
            name='student_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.studentclass'),
            preserve_default=False,
        ),
    ]
